[package]
name = "md-editor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
ropey = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
